#ifndef CROCODDYL_MULTIBODY_ACTUATIONS_DISTRIBUTED_THRUSTERS_HPP_
#define CROCODDYL_MULTIBODY_ACTUATIONS_DISTRIBUTED_THRUSTERS_HPP_

#include "crocoddyl/core/actuation-base.hpp"
#include "crocoddyl/multibody/states/multibody.hpp"
#include "pinocchio/algorithm/frames.hpp"
#include "pinocchio/algorithm/rnea-derivatives.hpp"

namespace crocoddyl {
enum DistributedThrusterType { DT_CW = 0, DT_CCW };
template <typename _Scalar>
struct DistributedThrusterTpl {
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW

  typedef _Scalar Scalar;
  typedef pinocchio::SE3Tpl<Scalar> SE3;
  typedef DistributedThrusterTpl<Scalar> DistributedThruster;
  typedef MathBaseTpl<Scalar> MathBase;
  typedef pinocchio::ForceTpl<Scalar> Force;
  typedef typename MathBase::Vector3s Vector3s;

  DistributedThrusterTpl(
      const int frame_id, const SE3& joint_M_thruster, const Scalar ctorque,
      const DistributedThrusterType direction = DT_CW,
      const Scalar min_thrust = Scalar(0.),
      const Scalar max_thrust = std::numeric_limits<Scalar>::infinity(),
      const Scalar delta_thrust_max = std::numeric_limits<Scalar>::infinity())
      : frame_id_(frame_id),
        joint_M_thruster_(joint_M_thruster),
        ctorque_(ctorque),
        direction_(direction),
        min_thrust_(min_thrust),
        max_thrust_(max_thrust),
        delta_thrust_max_(delta_thrust_max) {
    thrust_wrench_unit_.linear() = Vector3s(Scalar(0.), Scalar(0.), Scalar(1.));
    if (direction_ == DT_CW)
      thrust_wrench_unit_.angular() =
          Vector3s(Scalar(0.), Scalar(0.), ctorque_);
    else
      thrust_wrench_unit_.angular() =
          Vector3s(Scalar(0.), Scalar(0.), -ctorque_);

    thrust_wrench_unit_parent_joint_ =
        joint_M_thruster_.act(thrust_wrench_unit_);
  }

  template <typename NewScalar>
  DistributedThrusterTpl<NewScalar> cast() const {
    typedef DistributedThrusterTpl<NewScalar> ReturnType;
    ReturnType ret(frame_id_, joint_M_thruster_.template cast<NewScalar>(),
                   scalar_cast<NewScalar>(ctorque_), direction_,
                   scalar_cast<NewScalar>(min_thrust_),
                   scalar_cast<NewScalar>(max_thrust_),
                   scalar_cast<NewScalar>(delta_thrust_max_));
    return ret;
  }

  int frame_id_;          //!< Thruster frame id
  SE3 joint_M_thruster_;  //!< Thruster pose in the joint frame
  Scalar ctorque_;        //!< Coefficient of generated torque per thrust
  DistributedThrusterType
      direction_;      //!< Type of thruster (clockwise or counterclockwise)
  Scalar min_thrust_;  //!< Minimum thrust
  Scalar max_thrust_;  //!< Maximum thrust
  Scalar delta_thrust_max_;   //!< Maximum change of thrust (thrust rate limit)
  Force thrust_wrench_unit_;  //!< Unit wrench generated by the thruster at
                              //!< thruster frame
  Force
      thrust_wrench_unit_parent_joint_;  //!< Unit wrench at parent joint frame
};

template <typename _Scalar>
class ActuationModelFloatingBaseDistributedThrustersTpl
    : public ActuationModelAbstractTpl<_Scalar> {
 public:
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  CROCODDYL_DERIVED_CAST(ActuationModelBase,
                         ActuationModelFloatingBaseDistributedThrustersTpl)

  typedef _Scalar Scalar;
  typedef MathBaseTpl<Scalar> MathBase;
  typedef ActuationModelAbstractTpl<Scalar> Base;
  typedef ActuationDataFloatingBaseDistributedThrustersTpl<Scalar> Data;
  typedef ActuationDataAbstractTpl<Scalar> ActuationDataAbstract;
  typedef StateMultibodyTpl<Scalar> StateMultibody;
  typedef pinocchio::ModelTpl<Scalar> PinocchioModel;
  typedef DistributedThrusterTpl<Scalar> DistributedThruster;
  typedef typename MathBase::MatrixXs MatrixXs;
  typedef typename MathBase::VectorXs VectorXs;
  typedef typename MathBase::Vector6s Vector6s;
  typedef typename pinocchio::ForceTpl<Scalar> Force;

  ActuationModelFloatingBaseDistributedThrustersTpl(
      std::shared_ptr<StateMultibody> state,
      const std::vector<DistributedThruster>& thrusters)
      : Base(state,
             state->get_nv() -
                 state->get_pinocchio()
                     ->joints[(
                         state->get_pinocchio()->existJointName("root_joint")
                             ? state->get_pinocchio()->getJointId("root_joint")
                             : 0)]
                     .nv() +
                 thrusters.size()),
        state_(state),
        thrusters_(thrusters),
        n_thrusters_(thrusters.size()) {
    // Update the joint actuation part
    const std::size_t nv_f =
        state->get_pinocchio()
            ->joints[(state->get_pinocchio()->existJointName("root_joint")
                          ? state->get_pinocchio()->getJointId("root_joint")
                          : 0)]
            .nv();
    if (nu_ > n_thrusters_) {
      Base::u_lb_.tail(nu_ - n_thrusters_) =
          Scalar(-1.) * state_->get_pinocchio()->effortLimit.segment(
                            nv_f, nu_ - n_thrusters_);
      Base::u_ub_.tail(nu_ - n_thrusters_) =
          state_->get_pinocchio()->effortLimit.segment(nv_f,
                                                       nu_ - n_thrusters_);
    }

    zero_gravity_model_ =
        std::make_shared<PinocchioModel>(*(state_->get_pinocchio()));
    zero_gravity_model_->gravity.setZero();

    for (size_t i = 0; i < n_thrusters_; ++i) {
      Base::u_lb_(i) = thrusters_.at(i).min_thrust_;
      Base::u_ub_(i) = thrusters_.at(i).max_thrust_;
    }
  }

  virtual ~ActuationModelFloatingBaseDistributedThrustersTpl() = default;

  virtual void calc(
      const std::shared_ptr<ActuationDataAbstract>& data,
      const Eigen::Ref<const typename MathBase::VectorXs>& x,
      const Eigen::Ref<const typename MathBase::VectorXs>& u) override {
    const Eigen::VectorBlock<const Eigen::Ref<const VectorXs>, Eigen::Dynamic>
        q = x.head(state_->get_nq());

    Data* d = static_cast<Data*>(data.get());

    updateWThrust(d, q);

    data->dtau_du = d->W_thrust;
    data->tau = data->dtau_du * u;
  }

  virtual void calcDiff(
      const std::shared_ptr<ActuationDataAbstract>& data,
      const Eigen::Ref<const typename MathBase::VectorXs>& x,
      const Eigen::Ref<const typename MathBase::VectorXs>& u) override {
    const Eigen::VectorBlock<const Eigen::Ref<const VectorXs>, Eigen::Dynamic>
        q = x.head(state_->get_nq());

    Data* d = static_cast<Data*>(data.get());

    computeFExtByThrusts(u, d->fext);

    d->static_torque_partial_dq.setZero();

    pinocchio::computeStaticTorqueDerivatives(*(zero_gravity_model_),
                                              d->pinocchio, q, d->fext,
                                              d->static_torque_partial_dq);

    data->dtau_dx.leftCols(state_->get_nv()).noalias() =
        -d->static_torque_partial_dq;
    data->dtau_dx.rightCols(state_->get_nv()).setZero();
  }

  virtual void commands(const std::shared_ptr<ActuationDataAbstract>& data,
                        const Eigen::Ref<const VectorXs>& x,
                        const Eigen::Ref<const VectorXs>& tau) {
    const Eigen::VectorBlock<const Eigen::Ref<const VectorXs>, Eigen::Dynamic>
        q = x.head(state_->get_nq());

    Data* d = static_cast<Data*>(data.get());

    updateWThrust(d, q);

    updateActuationSet(d);
    data->u.noalias() = d->Mtau * tau;
  }

  virtual void torqueTransform(
      const std::shared_ptr<ActuationDataAbstract>& data,
      const Eigen::Ref<const VectorXs>& x,
      const Eigen::Ref<const VectorXs>&) override {
    Data* d = static_cast<Data*>(data.get());
    updateWThrust(d, x.head(state_->get_nq()));
    updateActuationSet(d);
  }

  virtual std::shared_ptr<ActuationDataAbstractTpl<Scalar>> createData()
      override {
    std::shared_ptr<Data> data =
        std::allocate_shared<Data>(Eigen::aligned_allocator<Data>(), this);

    initData(data);
    return data;
  }

  template <typename NewScalar>
  ActuationModelFloatingBaseDistributedThrustersTpl<NewScalar> cast() const {
    typedef ActuationModelFloatingBaseDistributedThrustersTpl<NewScalar>
        ReturnType;
    typedef StateMultibodyTpl<NewScalar> StateType;
    typedef DistributedThrusterTpl<NewScalar> DistributedThrusterType;
    std::vector<DistributedThrusterType> thrusters =
        vector_cast<NewScalar>(thrusters_);
    ReturnType ret(
        std::make_shared<StateType>(state_->template cast<NewScalar>()),
        thrusters);
    return ret;
  }

  /** @brief Return the vector of thrusters. */
  const std::vector<DistributedThruster>& get_thrusters() const {
    return thrusters_;
  }

  /** @brief Return the number of thrusters. */
  std::size_t get_nthrusters() const { return n_thrusters_; }

  virtual void print(std::ostream& os) const override {
    os << "ActuationModelFloatingBaseDistributedThrusters {nu=" << nu_
       << ", nthrusters=" << n_thrusters_ << "}";
  }

 protected:
  std::shared_ptr<PinocchioModel> zero_gravity_model_;
  std::shared_ptr<StateMultibody> state_;
  std::vector<DistributedThruster> thrusters_;  //!< List of thrusters
  std::size_t n_thrusters_;                     //!< Number of thrusters

  using Base::nu_;

 private:
  void updateWThrust(Data* d, const Eigen::Ref<const VectorXs>& q) {
    for (size_t i = 0; i < n_thrusters_; ++i) {
      d->tmp_thrust_jacobian.setZero();
      pinocchio::computeFrameJacobian(*(state_->get_pinocchio()), d->pinocchio,
                                      q, thrusters_.at(i).frame_id_,
                                      pinocchio::LOCAL, d->tmp_thrust_jacobian);

      d->W_thrust.col(i) = d->tmp_thrust_jacobian.transpose() *
                           thrusters_.at(i).thrust_wrench_unit_.toVector();
    }
  }

  void computeFExtByThrusts(const Eigen::Ref<const VectorXs>& u,
                            std::vector<Force>& fext) {
    for (auto& f : fext) f.setZero();

    for (size_t i = 0; i < n_thrusters_; i++) {
      pinocchio::JointIndex thruster_parent_joint_index =
          state_->get_pinocchio()->frames[thrusters_[i].frame_id_].parentJoint;

      fext.at(thruster_parent_joint_index) +=
          thrusters_[i].thrust_wrench_unit_parent_joint_ * u(i);
    }
  }

  /**
   * @brief Refresh the torque transform and the actuated subspace
   *
   * Both depend on the configuration through W(q), unlike in
   * `ActuationModelFloatingBaseThrustersTpl` where the thrusters are rigidly
   * attached to the root joint. They are only read by the inverse-dynamics
   * models, which call `commands()` and `torqueTransform()` beforehand, so
   * this (pseudo-inverse) is deliberately kept out of `calc()`.
   */
  void updateActuationSet(Data* d) {
    d->Mtau = pseudoInverse(d->W_thrust);
    d->S.noalias() = d->W_thrust * d->Mtau;
    for (std::size_t k = 0; k < state_->get_nv(); ++k) {
      d->tau_set[k] = if_static(d->S(k, k));
    }
  }

  void initData(const std::shared_ptr<Data>& data) {
    // Update the joint actuation part
    data->W_thrust.bottomRightCorner(nu_ - n_thrusters_, nu_ - n_thrusters_)
        .diagonal()
        .setOnes();
    updateActuationSet(data.get());
  }

  // Use for floating-point types
  template <typename Scalar>
  typename std::enable_if<std::is_floating_point<Scalar>::value, bool>::type
  if_static(const Scalar& condition) {
    return (fabs(condition) < std::numeric_limits<Scalar>::epsilon()) ? false
                                                                      : true;
  }

#ifdef CROCODDYL_WITH_CODEGEN
  // Use for CppAD types
  template <typename Scalar>
  typename std::enable_if<!std::is_floating_point<Scalar>::value, bool>::type
  if_static(const Scalar& condition) {
    return CppAD::Value(CppAD::fabs(condition)) >=
           CppAD::numeric_limits<Scalar>::epsilon();
  }
#endif
};

template <typename _Scalar>
struct ActuationDataFloatingBaseDistributedThrustersTpl
    : public ActuationDataAbstractTpl<_Scalar> {
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  typedef _Scalar Scalar;
  typedef MathBaseTpl<Scalar> MathBase;
  typedef ActuationDataAbstractTpl<Scalar> Base;
  typedef StateMultibodyTpl<Scalar> StateMultibody;
  typedef typename MathBase::MatrixXs MatrixXs;
  typedef pinocchio::ForceTpl<Scalar> Force;

  template <template <typename Scalar> class Model>
  explicit ActuationDataFloatingBaseDistributedThrustersTpl(
      Model<Scalar>* const model)
      : Base(model) {
    std::shared_ptr<StateMultibody> state =
        std::static_pointer_cast<StateMultibody>(model->get_state());
    pinocchio = pinocchio::DataTpl<Scalar>(*(state->get_pinocchio()));
    fext.resize(state->get_pinocchio()->njoints, Force::Zero());
    W_thrust = MatrixXs::Zero(model->get_state()->get_nv(), model->get_nu());
    tmp_thrust_jacobian = MatrixXs::Zero(6, model->get_state()->get_nv());
    static_torque_partial_dq = MatrixXs::Zero(model->get_state()->get_nv(),
                                              model->get_state()->get_nv());
    S = MatrixXs::Zero(model->get_state()->get_nv(),
                       model->get_state()->get_nv());
  }

  pinocchio::DataTpl<Scalar> pinocchio;  //!< Pinocchio data
  std::vector<Force> fext;
  MatrixXs W_thrust;
  MatrixXs tmp_thrust_jacobian;
  MatrixXs static_torque_partial_dq;
  MatrixXs S;

  using Base::dtau_du;
  using Base::dtau_dx;
  using Base::Mtau;
  using Base::tau;
  using Base::tau_set;
  using Base::u;
};

}  // namespace crocoddyl

CROCODDYL_DECLARE_EXTERN_TEMPLATE_STRUCT(crocoddyl::DistributedThrusterTpl)
CROCODDYL_DECLARE_EXTERN_TEMPLATE_CLASS(
    crocoddyl::ActuationModelFloatingBaseDistributedThrustersTpl)
CROCODDYL_DECLARE_EXTERN_TEMPLATE_STRUCT(
    crocoddyl::ActuationDataFloatingBaseDistributedThrustersTpl)
#endif
